# Generated by Django 4.1.2 on 2022-10-29 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_lyric_song_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyric',
            name='song_id',
        ),
    ]
